export const browseV2Jobs = [
  {
    id: 'v2-1',
    companyId: 'company-1',
    companyName: 'Nimbus Labs',
    title: 'Senior React Developer',
    description: 'We are looking for an experienced React developer to build and maintain our core SaaS dashboard. You will work closely with the design team to implement pixel-perfect UI components and integrate with our GraphQL API. Strong understanding of performance optimization and testing is required.',
    category: 'Web',
    skills: ['React', 'TypeScript', 'GraphQL', 'TailwindCSS'],
    budget: 8000,
    status: 'open',
    postedAt: '2026-09-10T10:00:00Z',
    applications: [],
    contractType: 'Solo Specialist',
    escrowAmount: 15000,
    escrowType: 'Milestone 1 Locked',
    hourlyRange: [130, 155],
    companyRating: 4.8,
    companyReviews: 28,
    companySpend: '$92k Spent',
    timeZone: 'US / Europe Overlap',
    duration: '3-Month Contract',
    hoursPerWeek: 40,
    seniority: 'Senior Specialist',
    milestoneSize: '$20k - $50k',
    workModality: 'US Hours Overlap',
  },
  {
    id: 'v2-2',
    companyId: 'company-2',
    companyName: 'Bluepeak',
    title: 'Flutter Mobile Developer',
    description: 'Join our mobile team to build cross-platform fintech applications. You will develop features for our payment processing app, implement secure authentication flows, and work with real-time transaction data. Experience with state management and CI/CD pipelines is a plus.',
    category: 'Mobile',
    skills: ['Flutter', 'Dart', 'Firebase', 'REST API'],
    budget: 7000,
    status: 'open',
    postedAt: '2026-09-09T08:00:00Z',
    applications: [
      { workerId: 'w-1', workerName: 'Sofia M.', appliedAt: '2026-09-10T14:00:00Z', status: 'pending' },
    ],
    contractType: 'Solo Specialist',
    escrowAmount: 12000,
    escrowType: 'Milestone 1 Locked',
    hourlyRange: [110, 145],
    companyRating: 4.9,
    companyReviews: 35,
    companySpend: '$180k Platform Spend',
    timeZone: 'Async Preferred',
    duration: '2-Month Contract',
    hoursPerWeek: 30,
    seniority: 'Senior Specialist',
    milestoneSize: '$20k - $50k',
    workModality: 'Async-First',
  },
  {
    id: 'v2-3',
    companyId: 'company-3',
    companyName: 'Vector Systems',
    title: 'QA Automation Engineer',
    description: 'We need a detail-oriented QA engineer to design and implement our automated testing suite. You will write end-to-end tests using Playwright, maintain CI pipelines, and help improve our overall code quality. Familiarity with desktop applications is preferred.',
    category: 'Desktop',
    skills: ['Playwright', 'Cypress', 'Jenkins', 'Python'],
    budget: 5500,
    status: 'open',
    postedAt: '2026-09-08T12:00:00Z',
    applications: [
      { workerId: 'w-2', workerName: 'David R.', appliedAt: '2026-09-09T09:00:00Z', status: 'accepted' },
      { workerId: 'w-3', workerName: 'Liam O.', appliedAt: '2026-09-10T11:00:00Z', status: 'pending' },
    ],
    contractType: 'Solo Specialist',
    escrowAmount: 18500,
    escrowType: 'Escrow Verified',
    hourlyRange: [90, 120],
    companyRating: 4.7,
    companyReviews: 19,
    companySpend: '$75k Spent',
    timeZone: 'Remote (EST 4h overlap)',
    duration: '6-Week Contract',
    hoursPerWeek: 40,
    seniority: 'Senior Specialist',
    milestoneSize: '$5k - $20k',
    workModality: 'US Hours Overlap',
  },
  {
    id: 'v2-4',
    companyId: 'company-1',
    companyName: 'Nimbus Labs',
    title: 'Security Auditor',
    description: 'Perform comprehensive security audits on our web applications and APIs. You will identify vulnerabilities, write detailed reports, and provide remediation guidance. Experience with OWASP top 10, penetration testing, and security tooling is essential.',
    category: 'Web',
    skills: ['Pentest', 'OWASP', 'Burp Suite', 'Node.js'],
    budget: 6000,
    status: 'open',
    postedAt: '2026-09-07T15:00:00Z',
    applications: [],
    contractType: 'Solo Specialist',
    escrowAmount: 12000,
    escrowType: 'Milestone 1 Locked',
    hourlyRange: [140, 185],
    companyRating: 5.0,
    companyReviews: 42,
    companySpend: '$450k+ Escrow Disbursed',
    timeZone: 'Remote (EST 4h overlap)',
    duration: '4-Week Contract',
    hoursPerWeek: 25,
    seniority: 'Staff / Principal',
    milestoneSize: '$5k - $20k',
    workModality: 'Async-First',
  },
  {
    id: 'v2-5',
    companyId: 'company-4',
    companyName: 'Horizon Web',
    title: 'E-commerce Frontend Developer',
    description: 'Build high-converting e-commerce experiences using Next.js and headless CMS. You will implement product pages, checkout flows, and performance optimizations. Strong eye for design and conversion optimization is required.',
    category: 'Web',
    skills: ['Next.js', 'TypeScript', 'Stripe', 'Sanity'],
    budget: 9000,
    status: 'closed',
    postedAt: '2026-08-20T10:00:00Z',
    applications: [
      { workerId: 'w-4', workerName: 'Elena R.', appliedAt: '2026-08-21T08:00:00Z', status: 'accepted' },
    ],
    contractType: 'Contract to Hire',
    escrowAmount: 18500,
    escrowType: 'Escrow Verified',
    hourlyRange: [130, 155],
    companyRating: 4.9,
    companyReviews: 15,
    companySpend: '$92k Spent',
    timeZone: 'US / Europe Overlap',
    duration: '2-Month Contract',
    hoursPerWeek: 40,
    seniority: 'Senior Specialist',
    milestoneSize: '$20k - $50k',
    workModality: 'US Hours Overlap',
  },
  {
    id: 'v2-6',
    companyId: 'company-5',
    companyName: 'Pocketcast Apps',
    title: 'Backend API Developer',
    description: 'Develop and maintain RESTful APIs for our consumer utility apps. You will design database schemas, implement authentication, and build real-time features using WebSockets. Go or Node.js experience preferred.',
    category: 'Mobile',
    skills: ['Node.js', 'Go', 'PostgreSQL', 'WebSockets'],
    budget: 6500,
    status: 'open',
    postedAt: '2026-09-05T09:00:00Z',
    applications: [],
    contractType: 'Solo Specialist',
    escrowAmount: 25000,
    escrowType: 'Escrow Locked',
    hourlyRange: [125, 160],
    companyRating: 4.8,
    companyReviews: 22,
    companySpend: '$310k Platform Spend',
    timeZone: 'Async Preferred',
    duration: '6-Week Contract',
    hoursPerWeek: 30,
    seniority: 'Senior Specialist',
    milestoneSize: '$20k - $50k',
    workModality: 'Async-First',
  },
  {
    id: 'v2-7',
    companyId: 'company-6',
    companyName: 'Fiberline',
    title: 'Browser Extension Developer',
    description: 'Create privacy-focused browser extensions for Chrome and Firefox. You will build content scripts, background workers, and popup UIs. Experience with WebExtensions API and Manifest V3 is essential.',
    category: 'Browser',
    skills: ['JavaScript', 'WebExtensions', 'Manifest V3', 'HTML/CSS'],
    budget: 4500,
    status: 'open',
    postedAt: '2026-09-04T14:00:00Z',
    applications: [
      { workerId: 'w-5', workerName: 'Marcus T.', appliedAt: '2026-09-05T10:00:00Z', status: 'pending' },
    ],
    contractType: 'Solo Specialist',
    escrowAmount: 12000,
    escrowType: 'Milestone 1 Locked',
    hourlyRange: [110, 145],
    companyRating: 4.6,
    companyReviews: 12,
    companySpend: '$75k Spent',
    timeZone: 'North America / EU',
    duration: '4-Week Contract',
    hoursPerWeek: 25,
    seniority: 'Senior Specialist',
    milestoneSize: '$5k - $20k',
    workModality: 'US Hours Overlap',
  },
  {
    id: 'v2-8',
    companyId: 'company-7',
    companyName: 'Quantum Soft',
    title: 'Full-Stack Dashboard Developer',
    description: 'Build enterprise-grade data dashboards and reporting tools. You will work with React on the frontend and Node.js on the backend, integrating with complex data pipelines. Experience with charting libraries and data visualization is required.',
    category: 'Desktop',
    skills: ['React', 'Node.js', 'D3.js', 'PostgreSQL'],
    budget: 10000,
    status: 'open',
    postedAt: '2026-09-03T11:00:00Z',
    applications: [],
    contractType: 'Contract to Hire',
    escrowAmount: 18500,
    escrowType: 'Escrow Verified',
    hourlyRange: [130, 155],
    companyRating: 4.9,
    companyReviews: 15,
    companySpend: '$92k Spent',
    timeZone: 'US / Europe Overlap',
    duration: '3-Month Contract',
    hoursPerWeek: 40,
    seniority: 'Senior Specialist',
    milestoneSize: '$20k - $50k',
    workModality: 'US Hours Overlap',
  },
]

export const featuredSquad = {
  id: 'squad-1',
  title: 'Fintech Core Banking Re-Architecture — 4-Person Squad',
  companyName: 'AetherPay Technologies',
  companyVerified: true,
  companyRating: 5.0,
  companyReviews: 42,
  companySpend: '$450k+ Escrow Disbursed',
  description: 'Re-architecting our payment ledger engine to sub-millisecond transactional latency using asynchronous event loops and Raft consensus. Turnkey sprint with dedicated DevOps pipeline and formal verification auditor.',
  monthlyEscrow: 32000,
  hourlyRange: [120, 160],
  duration: '3-Month Contract',
  hoursPerWeek: 40,
  timeZone: 'Remote (EST 4h overlap)',
  skills: ['Rust', 'Tokio', 'gRPC', 'PostgreSQL', 'Docker', 'AWS Fargate'],
  contractType: 'Turnkey Squad',
  postedAt: '2026-09-10T07:00:00Z',
  roster: [
    { role: 'Lead Rust Architect', status: 'filled' },
    { role: 'Sr. Systems Engineer', status: 'open', slots: 1 },
    { role: 'Security Auditor', status: 'open', slots: 1 },
  ],
}

export const quickFilters = [
  'All Roles',
  'Turnkey Squad Openings',
  'Solana / Rust',
  'React & Next.js',
  'Cloud & DevOps',
  'AI / LLM Orchestration',
  'Security & Pen-Testing',
  '$100+/hr',
]
